#Nom de l'exécutable final
TARGET = bitthune_exec

#Compilateur et options
CC = gcc
CFLAGS = -Wall -Wextra -g -Iinclude
#LDFLAGS = -lssl -lcrypto # a decommenter pour la Partie 3 (OpenSSL)

#Dossiers
SRC_DIR = src
LIB_DIR = lib
OBJ_DIR = obj

#fichiers sources dans src et lib
SRC_FILES = $(wildcard $(SRC_DIR)/*.c) $(wildcard $(LIB_DIR)/*.c)
#fichiers objest dans src et lib
OBJ_FILES = $(patsubst %.c, $(OBJ_DIR)/%.o, $(notdir $(SRC_FILES)))

#Regle principale
all: $(OBJ_DIR) $(TARGET)

#Creation de l'exécutable
$(TARGET): $(OBJ_FILES)
	$(CC) $(OBJ_FILES) -o $@ $(LDFLAGS)

#Compilation des fichiers objets
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(LIB_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

#Creer le dossier obj s'il n'existe pas
$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

#Nettoyage des fichiers temporaires
clean:
	rm -rf $(OBJ_DIR) $(TARGET)

.PHONY: all clean