#Nom de l'exécutable final
TARGET = bitthune_exec

#Compilateur et options
CC = gcc
CFLAGS = -Wall -Wextra -g -Iinclude -Ilib -Ilib/Sha256
#LDFLAGS = -lssl -lcrypto # a decommenter pour la Partie 3 (OpenSSL)

ifeq ($(OS),Windows_NT)
MKDIR_P = if not exist $(OBJ_DIR) mkdir $(OBJ_DIR)
CLEAN_CMD = del /Q $(OBJ_DIR)\\*.o 2>nul & rmdir /S /Q $(OBJ_DIR) 2>nul & del /Q $(TARGET).exe $(TARGET) *.json 2>nul
else
MKDIR_P = mkdir -p $(OBJ_DIR)
CLEAN_CMD = rm -rf $(OBJ_DIR) $(TARGET) *.json
endif

#Dossiers
SRC_DIR = src
LIB_DIR = lib
OBJ_DIR = obj

#fichiers sources dans src et lib
SRC_FILES = $(wildcard $(SRC_DIR)/*.c) \
            $(LIB_DIR)/Sha256/sha256.c \
            $(LIB_DIR)/Sha256/sha256_utils.c
#fichiers objest dans src et lib
OBJ_FILES = $(patsubst %.c, $(OBJ_DIR)/%.o, $(notdir $(SRC_FILES)))
vpath %.c $(SRC_DIR) $(LIB_DIR) $(LIB_DIR)/Sha256


#Regle principale
all: $(OBJ_DIR) $(TARGET)

$(TARGET): $(OBJ_FILES)
	$(CC) $(OBJ_FILES) -o $@ $(LDFLAGS)

$(OBJ_DIR)/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Créer le dossier obj s'il n'existe pas
$(OBJ_DIR):
	$(MKDIR_P)

# Nettoyage
clean:
	$(CLEAN_CMD)

.PHONY: all clean